#!/usr/bin/env node
'use strict';

var path = require('path');
var fs = require('fs');

var targetDir = path.join(__dirname, '../app/benchmark/');
var start = 0;
var end = 99;
var pad = '00';

var html = fs.readFileSync(targetDir + 'index.html');
var jade = fs.readFileSync(targetDir + 'index.jade');
var filename;
var i;

for (i = start; i <= end; i++) {
    filename = (pad + i).slice(-pad.length);
    fs.writeFileSync(targetDir + filename + '.html', html);
    fs.writeFileSync(targetDir + filename + '.jade', jade);
}
